image: node:latest

stages:
  - lint
  - build

before_script:
  - npm install

eslint:
  stage: lint
  when: always
  script:
    - npm run lint

build:
  stage: build
  when: always
  script:
    - npm run build
