image: node:latest

stages:
  - lint
  - build

before_script:
  - npm install
  - echo "$CONFIGURATION" > src/models/config.js

eslint:
  stage: lint
  when: always
  script:
    - npm run lint

build:
  stage: build
  when: always
  script:
    - npm run build
