image: node:latest

stages:
  - lint
  - test
  - build

before_script:
  - npm install

eslint:
  stage: lint
  when: always
  script:
    - npm run lint

test:
  stage: test
  when: always
  script:
    - npm run test

build:
  stage: build
  when: always
  script:
    - npm run build
